version: "3"

services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongodb:27017/expressnext_db
